### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by noraesae** [KokoIRC/koko#28]
I am really sorry to say this, but this project may not be continued, at least by me. Currently, I don't have enough time and resource to contribute and maintain this project, mainly because of my professional works and also other personal things having higher priority. I think it would be better to look for new maintainers for this project, rather than letting users and contributors disappointed. If there is anybody interested in maintaining Koko, please leave a comment or contact me via email.

The handover could be done in several forms:

- Fork the project and create another repository
  - You can use 'Fork' of GitHub, or just clone and push to a new repository. You can even change the project name and don't need to mention it's a fork(if you want, you can surely do).
  - When the new repository is created, I will mark this repository deprecated and introduce the new project URL.
- Just keep the repository here and add new maintainers to collaborators
  - This way is simpler, but may look less obvious that I am off for the maintenance.

Both options are completely fine to me, so please let me know how it shall be done.

Sorry again, and thanks for your interests on the project.

**Comment by garetmckinley** [comment]
I don't have time to maintain it full time, but I'd love to be one of the people maintaining this project. I actually just acquired [jsb.ro](http://jsb.ro) and am in the process of trying to acquire a good GitHub org name for it to host open source projects under.

If enough people are interested, maybe we could get a group together and maintain it under that org? If an org that's already established wants to maintain it, that's cool too, but I'd love to be a part of it if possible 😸

**Comment by noraesae** [comment]
It looks also nice that a group maintains Koko, though I'm not sure I can be a member of it and continue to contribute. If anybody want to take this project over as a group, please feel free to let me know.

**Comment by garetmckinley** [comment]
Exactly. Hopefully some people are interested in joining!

**Comment by mmarkman** [comment]
Please add me as a maintainer! I'll look into creating a group/organization on github in the coming months if this starts getting more attention.

**Comment by noraesae** [comment]
Great to hear you guys are interested. I think this project is not too big for a small group of people to maintain, two or three will be good enough. Would you create a repository, possible on a GH org?

**Comment by mmarkman** [comment]
I just created koko-maintainers organization, can you transfer the repo to this org?

**Comment by mmarkman** [comment]
I invited @noraesae @garetmckinley

**Comment by garetmckinley** [comment]
I joined, I think it would be better to name it something like KokoIRC or something though, the name is a bit long. But that's just a personal nitpick. Looking forward to being a part of koko's future.

**Comment by mmarkman** [comment]
done @garetmckinley, now KokoIRC

**Comment by noraesae** [comment]
I've finished transfer. The org name can be changed later at anytime, so may be not a big deal now.

Thanks for inviting me in the org, but I may not be very active on contribution. Will try to keep tracking as much as possible though.

I close this issue now. If there are others interested in this project, please feel free to leave further comments.

Thanks again!

**Comment by garetmckinley** [comment]
What's your email @mmarkman? I setup a slack room for kokoirc and I'm inviting you to it. That way we can have better communication, especially when more people join the project.

**Comment by billybonks** [comment]
Isn't it funny setting up a slack room for and it client :)?

**Comment by garetmckinley** [comment]
To a degree it seems a bit silly, but unless someone is willing to program a few bots for an IRC client, slack is far superior for making team decisions. If not for anything else, for the polling features.

@mmarkman do you mind bumping me up in the kokoIRC org so I have write access to the repo? For this project to move healthily forward, we need multiple people able to manage the repo. I would like to run through the issues and tag everything. This project was built solo, and it shows. We need to make it open source friendly if we want it to be successful and get community support.
